version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3000:3000'
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g       # Limit memory to 2GB
        reservations:
          memory: 1g       # Reserve 1GB of memory

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8001:8001'  # Используем порт 8080 для HTTP
      - '4435:4435'  # Порт 443 остается для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextjs
    deploy:
      resources:
        limits:
          memory: 512m     # Limit memory to 512MB
        reservations:
          memory: 256m     # Reserve 256MB of memory
