version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3000:3000'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'       # Standard HTTP port
      - '443:443'     # Standard HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextjs
