version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"  # Expose HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX configuration
      - /etc/letsencrypt:/etc/letsencrypt   # Mount Let's Encrypt certs inside the container
    depends_on:
      - nextjs
