version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3000:3000'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8001:8001' 
      - '4435:4435' 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextjs
