version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3000:3000'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80' # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # NGINX config file
    depends_on:
      - nextjs
