version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3000:3000'
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8001:8001' # Используем порт 8080 для HTTP
      - '443:443' # Порт 443 остается для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextjs
